### ISSUE TITLE
Make a Image slider using html css & javascript with good design

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#100]

**Comment by harshvyas-22** [comment]
i would love to work on this section can you assign it me

**Comment by 08Uzair** [comment]
Please assign this to me i can do your work in 1-2hrs

**Comment by harshal255** [comment]
> i would love to work on this section can you assign it me

Yeah sure

**Comment by harshal255** [comment]
> Please assign this to me i can do your work in 1-2hrs

Yeah sure
