### ISSUE TITLE
Make a logo for main website (unique javascript)

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#11]

**Comment by DarkSoul26** [comment]
@harshal255 please assign it to me

**Comment by harshal255** [comment]
> @harshal255 please assign it to me

Okayy

**Comment by GeeekySouro003** [comment]
Hello sir i will be very grateful if i get the oppurtunity to work on this.Please assign me on this.

**Comment by harshal255** [comment]
> Hello sir i will be very grateful if i get the oppurtunity to work on this.Please assign me on this.

Yeahh brother

**Comment by DarkSoul26** [comment]
Will you?

**Comment by GreenyNg** [comment]
Please assign this to me. I would love to work on this

**Comment by GreenyNg** [comment]
Please assign me to this. I want to work on it!

**Comment by GreenyNg** [comment]
Please assign me to this. Thanks.

**Comment by DarkSoul26** [comment]
Hey @harshal255, please check #31

**Comment by harshal255** [comment]
> Hey @harshal255, please check #31

okayy
