### ISSUE TITLE
Add Data Structure & Algorithms Questions using Javascript 🚀🚀

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#12]

**Comment by moinsid** [comment]
I want to contribute please assign me @harshal255

**Comment by rishtwij2407** [comment]
I want to contibute in this task.....kindly assign it to me

**Comment by harshal255** [comment]
> I want to contribute please assign me @harshal255

Okayy..

**Comment by harshal255** [comment]
> I want to contibute in this task.....kindly assign it to me

Okayy

**Comment by moinsid** [comment]
can you brief me because it is my first repo @harshal255

**Comment by harshal255** [comment]
> can you brief me because it is my first repo @harshal255
Yeahh
Watch these two video for open-source contribution
https://www.youtube.com/live/DZ-_Yd_-44Q?si=gFV5Bp7BgWbxBARr
https://youtu.be/3rksDnlcgdU?si=er1MjpIYMHk-S7ox

**Comment by moinsid** [comment]
ok thank you

**Comment by ashfaque-mustaque** [comment]
@harshal255 i want to contribute to your repo. 
can you assign me

**Comment by harshal255** [comment]
> @harshal255 i want to contribute to your repo. can you assign me

okay

**Comment by HarshallSonawane** [comment]
Hey @harshal255 ,
can you assign me this issue

**Comment by harshal255** [comment]
> Hey @harshal255 , can you assign me this issue

okayy

**Comment by harshal255** [comment]
> @harshal255 i want to contribute to your repo. can you assign me

yeahh
