### ISSUE TITLE
Make a website that containes all open source organizations with good ui

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#124]

**Comment by SoldierCorp** [comment]
@harshal255 Are you serious about this? Hacktoberfest is meant to encourage contributions to existing projects, not to have an entire project built for free.

**Comment by harshal255** [comment]
> @harshal255 Are you serious about this? Hacktoberfest is meant to encourage contributions to existing projects, not to have an entire project built for free.

Yes, I am serious, & I just want to website that contains important projects using HTML, CSS and JavaScript.
