### ISSUE TITLE
add Drag & drop website using html css & javascript

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#125]

**Comment by chiku011** [comment]
hii, can you assign this issue to me

**Comment by harshal255** [comment]
Yesh you can work on this feature
I will assign you 👍🏻

Harshal Kahar
On 23 Oct 2023, 12:20 PM +0530, chiku011 ***@***.***>, wrote:

hii, can you assign this issue to me

**Comment by 08Uzair** [comment]
Please Assign this to me

**Comment by Piyush07p** [comment]
plz assign me this
