### ISSUE TITLE
Adding new unique javascript projects 

### ISSUE THREAD

**Issue by Kriagr23** [harshal255/Unique-Javascript#17]
i want to add my project kindly assign this issue to me @harshal255

**Comment by Arnav7107** [comment]
Hey @harshal255, I would love to add a new project. Can you please assign it to me?

**Comment by harshal255** [comment]
> Hey @harshal255, I would love to add a new project. Can you please assign it to me?

Yeah okay

**Comment by Vishusingh16** [comment]
can you assign me this issue?

**Comment by harshal255** [comment]
Yeah you can👍🏻


Harshal Kahar
On 10 Oct 2023, 10:28 PM +0530, Vaishnav Singh ***@***.***>, wrote:

can you assign me this issue?

**Comment by HarshallSonawane** [comment]
Hello @harshal255 can you assign me this issue, 
I plan on developing a drummer app using javascript

**Comment by harshal255** [comment]
> Hello @harshal255 can you assign me this issue, I plan on developing a drummer app using javascript

Okayy

**Comment by harshal255** [comment]
> can you assign me this issue?

 Okayy

**Comment by KartikeyCode** [comment]
Hi I have made a pull request to add my web3 project called bookspersecond
Hope you like it :D
