### ISSUE TITLE
Add an unique project build with html, css & javascript🤝

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#2]
## 📌Note: we want to make all project's UI unique type so don't use bootstrap CSS if you want to use tailwind CSS therefore it's fine🤝👍
if you want to refer unique type UI then the below repository :
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/bc1d3e1a-f2e2-45f2-89ab-e596cd0596b7)

**Comment by GriffinAnnshual** [comment]
Hey @harshal255 I would like to work on this issue as well. I guess I can complete this asap!

**Comment by MKisKrazy** [comment]
@harshal255 Hi, is a rock paper scissors website with autoplay feature and local storage enabled acceptable?

**Comment by harshal255** [comment]
> @harshal255 Hi, is a rock paper scissors website with autoplay feature and local storage enabled acceptable?

yes, you can contribute

**Comment by Kriagr23** [comment]
@harshal255 Hi, is a guess the number game acceptable?

**Comment by harshal255** [comment]
> @harshal255 Hi, is a guess the number game acceptable?

yeahh

**Comment by Kriagr23** [comment]
> > @harshal255 Hi, is a guess the number game acceptable?
> 
> yeahh

Kindly open the issue so that i can push a pull request

**Comment by Kriagr23** [comment]
> > @harshal255 Hi, is a guess the number game acceptable?
> 
> yeahh

kindly open this issue again so that I can add the project
