### ISSUE TITLE
Add Navbar 

### ISSUE THREAD

**Issue by ashfaque-mustaque** [harshal255/Unique-Javascript#21]
@harshal255 I want to add navbar to the page which will make the site more effective and also i will do the change the cards style.

so can you assign me this task to me .

**Comment by harshal255** [comment]
Yeahh brother

**Comment by ashfaque-mustaque** [comment]
assign me i will add navbar

**Comment by Piyush07p** [comment]
can you assign me this

**Comment by harshal255** [comment]
> can you assign me this

Okayy

**Comment by Piyush07p** [comment]
@harshal255 can you tell what sort of thing we have to add in navbar like home, about...
