### ISSUE TITLE
Add Javascript Interview Questions using javascript (ES6++) ✨

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#3]

**Comment by arpitasen20** [comment]
can i work on this issue?

**Comment by harshal255** [comment]
> can i work on this issue?

Yeahh you can

**Comment by RohanMalik2710** [comment]
Can you provide more details on the issue?

**Comment by harshal255** [comment]
> can i work on this issue?

you can add some javascript imp questions

**Comment by Luwa-Tech** [comment]
hey @harshal255 is this issue still open, i would like to work on it.

**Comment by Luwa-Tech** [comment]
okay but where would you like me to add the interview questions. I was thinking of creating a new file similar to the readme and add the questions instead. will that be good enough?

**Comment by harshal255** [comment]
> okay but where would you like me to add the interview questions. I was thinking of creating a new file similar to the readme and add the questions instead. will that be good enough?

Yeah that's enough

**Comment by Ankitv003** [comment]
hey, harshal, is this issue still open , can i also on this? this would be my first pr!

**Comment by sujithyadav998** [comment]
Hello @harshal255, I'm new to open source and eager to contribute. Could you please assign this issue to me?

**Comment by harshal255** [comment]
> hey, harshal, is this issue still open , can i also work on this? this would be my first pr!

Yeah sure

**Comment by harshal255** [comment]
> Hello @harshal255, I'm new to open source and eager to contribute. Could you please assign this issue to me?

Yeah sure

**Comment by Godswil-Uche** [comment]
Hello, @harshal255 I'm new to Open source and I will like to contribute to this. Is the room of contribution still open??
