### ISSUE TITLE
Scroll bar design can be improved

### ISSUE THREAD

**Issue by youtanimstar** [harshal255/Unique-Javascript#32]
Hi @harshal255 ,
While browsing this website, I noticed that the UI is very impressive, but the scrollbar does not match the overall UI of the website. Therefore, I believe I can improve this. Please assign this task to me.

here is the screenshot of the scroll bar.

![Screenshot from 2023-10-14 20-02-38](https://github.com/harshal255/Unique-Javascript/assets/107903218/626e7fbd-f243-43ca-9adb-fafadf01c423)

**Comment by harshal255** [comment]
> Hi @harshal255 , While browsing this website, I noticed that the UI is very impressive, but the scrollbar does not match the overall UI of the website. Therefore, I believe I can improve this. Please assign this task to me.
> 
> here is the screenshot of the scroll bar.
> 
> ![Screenshot from 2023-10-14 20-02-38](https://user-images.githubusercontent.com/107903218/275237283-626e7fbd-f243-43ca-9adb-fafadf01c423.png)

Yeah sure brother

**Comment by youtanimstar** [comment]
Thank you for assigning this task to me. I will do my best. 😊
