### ISSUE TITLE
Add a random generator quotes website 

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#4]
initially, store all quotes using json file & then generate a random value to access a particular number.

## 📌Note: we want to make all project's UI unique type so don't use bootstrap CSS if you want to use tailwind CSS therefore it's fine🤝👍
if you want to refer unique type UI then the below repository :
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/bc1d3e1a-f2e2-45f2-89ab-e596cd0596b7)

**Comment by PrathameshTheurkar** [comment]
hey @harshal255 can u assign this issue to me , I would love  to contribute to this issue .

**Comment by harshal255** [comment]
> hey @harshal255 can u assign this issue to me , I would love to contribute to this issue .

Okayy..

**Comment by PrathameshTheurkar** [comment]
I have made a PR #10 . Plz do check and let me know if need any changes .
