### ISSUE TITLE
Adding a BlackJack game using Javascript

### ISSUE THREAD

**Issue by HarshallSonawane** [harshal255/Unique-Javascript#40]
I want to add an interesting Blackjack game developed using javascript with great UI/UX experience for user. Can you please assign me with this!?

**Comment by harshal255** [comment]
> I want to add an interesting Blackjack game developed using javascript with great UI/UX experience for user. Can you please assign me with this!?

Yeah sure

**Comment by HarshallSonawane** [comment]
Please add the hacktoberfest label to this issue @harshal255

**Comment by harshal255** [comment]
> Please add the hacktoberfest label to this issue @harshal255

do you work on this issue??

**Comment by HarshallSonawane** [comment]
Not yet, I got occupied with some other task but I will be finishing it tomorrow or day after tomorrow for sure! 
sorry for the delay

**Comment by harshal255** [comment]
> Not yet, I got occupied with some other task but I will be finishing it tomorrow or day after tomorrow for sure! sorry for the delay

Okay np
