### ISSUE TITLE
Code a Stick Hero game with JavaScript and HTML Canvas

### ISSUE THREAD

**Issue by HarshallSonawane** [harshal255/Unique-Javascript#41]
To code an interactive version of the popular game 'Stick hero' using Javascript and HTML canvas. 
Stick hero game video for reference :  https://www.youtube.com/shorts/tKkwIs7lmJ0

Please assign me with this issue @harshal255 as I wish to contribute.

**Comment by harshal255** [comment]
> To code an interactive version of the popular game 'Stick hero' using Javascript and HTML canvas. Stick hero game video for reference : https://www.youtube.com/shorts/tKkwIs7lmJ0
> 
> Please assign me with this issue @harshal255 as I wish to contribute.

Yeah okay

**Comment by HarshallSonawane** [comment]
May I know whether would it be considered under the hacktoberfest label as I am eager to participate for the same!

**Comment by harshal255** [comment]
> May I know whether would it be considered under the hacktoberfest label as I am eager to participate for the same!

yes
