### ISSUE TITLE
Contribution: Add a Fall game with GUI and sound

### ISSUE THREAD

**Issue by Ayushkumargit7** [harshal255/Unique-Javascript#46]
In this contribution, I aim to develop and integrate a "Fall Game" game into the repository. 
It is a fun game to play.

Screenshot:
![image](https://github.com/harshal255/Unique-Javascript/assets/114018461/f9bc3868-a1b7-47f0-9a5c-9fa2f1f7bb65)

**Comment by Ayushkumargit7** [comment]
@harshal255  Please assign me the above issue.

**Comment by harshal255** [comment]
> @harshal255 Please assign me the above issue.

yeah sure
