### ISSUE TITLE
Add a random coding meme generator website

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#5]
## Add a random coding meme generator website
1. initially, store images in a particular directory 
2.  make a json file to access all images for optimization
3.  then generate a random value in index.html to access a particular meme.
4.  after some time period time , the meme should be changed,
5.  make a button as well to change a meme
## 📌Note: we want to make all project's UI unique type so don't use bootstrap CSS if you want to use tailwind CSS therefore it's fine🤝👍
if you want to refer unique type UI then the below repository :
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/bc1d3e1a-f2e2-45f2-89ab-e596cd0596b7)

**Comment by GriffinAnnshual** [comment]
Hey @harshal255 I would like to work on this

**Comment by harshal255** [comment]
Okayy

**Comment by Vishusingh16** [comment]
can you assign me this issue

**Comment by harshal255** [comment]
> can you assign me this issue

do you work on this issue??

**Comment by harshal255** [comment]
> Hey @harshal255 I would like to work on this

do you work in this issue??

**Comment by Ankitv003** [comment]
hey harshal , anybody working on this , can i contribute to this?

**Comment by harshal255** [comment]
> hey harshal , anybody working on this , can i contribute to this?

yes

**Comment by Piyush07p** [comment]
hey @harshal255  can you assign it to me

**Comment by harshal255** [comment]
> hey @harshal255 can you assign it to me

okayy
