### ISSUE TITLE
Music Visualization tool

### ISSUE THREAD

**Issue by JuanitaCathy** [harshal255/Unique-Javascript#57]
Hello! 
A real time music visualization tool which uses Web Audio API to analyze and create animations and effects
based on the rhythm, beats etc using Javascript.

**Comment by JuanitaCathy** [comment]
@harshal255 Please assign me this issue under Hacktoberfest, Thank you!

**Comment by harshal255** [comment]
> Hello! A real time music visualization tool which uses Web Audio API to analyze and create animations and effects based on the rhythm, beats etc using Javascript.

great

**Comment by harshal255** [comment]
> @harshal255 Please assign me this issue under Hacktoberfest, Thank you!

yeah sure..
