### ISSUE TITLE
Add a Strong Password Generator website using html css & js

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#6]
## 📌Note: we want to make all project's UI unique type so don't use bootstrap CSS if you want to use tailwind CSS therefore it's fine🤝👍
if you want to refer unique type UI then the below repository :
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/ebd53c9a-4fce-4371-af4e-9b2b666be212)

**Comment by bangadam** [comment]
Hi @harshal255, I can work on this issue please assign it to me.

**Comment by harshal255** [comment]
Okay..👍

**Comment by Piyush07p** [comment]
i will work for plz assign me

**Comment by Piyush07p** [comment]
hey @harshal255 plz allow the permission to push i have made the solution to this issue

**Comment by harshal255** [comment]
> hey @harshal255 plz allow the permission to push i have made the solution to this issue

you can make pull request, I will merge
