### ISSUE TITLE
Contribution: Add a GitHub Detective website 

### ISSUE THREAD

**Issue by adi-ray** [harshal255/Unique-Javascript#66]
### Description :
The website will work with the help of GitHub API and will display complete stats of that particular developer. 

### Features:

- Compatible both for dark and light modes.
- Search functionality added.
- Appropriate pop-up if no user is found.

### Screenshots:

![image](https://github.com/harshal255/Unique-Javascript/assets/96347576/182debd1-fb2a-4592-81a5-370cdb9f5d60)

![image](https://github.com/harshal255/Unique-Javascript/assets/96347576/fdfefd93-a9f9-4c95-a512-ef48a3b9a0af)

### Live Demo: [GitHub Detective](https://adi-ray.github.io/GitHub-Detective/)

**Comment by harshal255** [comment]
> @harshal255 Could you please assign me this issue !!

Yeah sure..
