### ISSUE TITLE
Contribution: Add a Form Validation Website in Javascript 

### ISSUE THREAD

**Issue by Ayushkumargit7** [harshal255/Unique-Javascript#67]
In this contribution, I aim to develop and integrate into the repository. A Form Validation Website , having input fields like name, email, password, etc. It is used to prevent errors by checking the data entered by the user for errors such as empty fields, invalid characters.Ensures the data is accurate. Prevent the mistakes of user inputing wrong data/format by giving errors. into the repository.

Ensures accurate data to be filled by the user.

Screenshot:
![image](https://github.com/harshal255/Unique-Javascript/assets/114018461/d8efd834-7e69-474c-b7aa-46eb65b54b86)

**Comment by Ayushkumargit7** [comment]
@harshal255  Please assign me the above issue.

**Comment by Ayushkumargit7** [comment]
@harshal255  You forgot to assign.

**Comment by harshal255** [comment]
> @harshal255 can you assign this issue/task to me under hacktoberfest label?

yeah

**Comment by harshal255** [comment]
> @harshal255 You forgot to assign.

okay

**Comment by Piyush07p** [comment]
can you assign me for this
