### ISSUE TITLE
Drum Kit Player using JS

### ISSUE THREAD

**Issue by EswarBenarjee** [harshal255/Unique-Javascript#69]
I wanted to add a Drum Kit project. Please assign this to me. @harshal255

**Comment by harshal255** [comment]
> I wanted to add a Drum Kit project. Please assign this to me. @harshal255

Yeah i will

**Comment by harshal255** [comment]
> I wanted to add a Drum Kit project. Please assign this to me. @harshal255

do you work on this issue??

**Comment by EswarBenarjee** [comment]
I guess this has been developed. Can I develop Simon's game? @harshal255

**Comment by harshal255** [comment]
> I guess this has been developed. Can I develop Simon's game? @harshal255

Okay I will check
