### ISSUE TITLE
Add a Alarm Clock website using html,css & javascript 

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#7]
📌Note: we want to make all project's UI unique type so don't use bootstrap CSS if you want to use tailwind CSS therefore it's fine🤝👍
if you want to refer unique type UI then the below repository :
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/058e6bfd-79a9-476f-998e-bd05a7f0b21b)

**Comment by GriffinAnnshual** [comment]
Hey @harshal255 I would like to work on this issue. Can you assign it to me?

**Comment by harshal255** [comment]
Yeahh👍

**Comment by harshal255** [comment]
> heyy @harshal255 can I work on this issue . Can you assign this to me ??

Okayy

**Comment by PrathameshTheurkar** [comment]
I have made a PR #15 plz do check and tell if needed any changes.
