### ISSUE TITLE
Minesweeper with Vanilla JavaScript

### ISSUE THREAD

**Issue by Shuhua-L** [harshal255/Unique-Javascript#70]
I'd like to add Minesweeper developed using JavaScript. Can you assign this issue to me with the 'hacktoberfest' tag?

**Comment by harshal255** [comment]
> I'd like to add Minesweeper developed using JavaScript. Can you assign this issue to me with the 'hacktoberfest' tag?

Yeah i will

**Comment by Shuhua-L** [comment]
@harshal255 Could you please add the 'hacktoberfest' tag? It seems you forgot it
