### ISSUE TITLE
Whack A Mole

### ISSUE THREAD

**Issue by karankhatri6** [harshal255/Unique-Javascript#77]
I wanted to add a Whack A Mole game created using JavaScript. Please assign this to me. @harshal255

**Comment by harshal255** [comment]
> I wanted to add a Whack A Mole game created using JavaScript. Please assign this to me. @harshal255

yeah sure

**Comment by karankhatri6** [comment]
Hey, @harshal255 Could you please check into why the projects on pages 2 and 3 are not opening? and can you please give this issue an hacktoberfest label

**Comment by harshal255** [comment]
> Hey, @harshal255 Could you please check into why the projects on pages 2 and 3 are not opening? and can you please give this issue an hacktoberfest label

yes I saw that bugs , I'll give you that issue👍👍
