### ISSUE TITLE
Add a developer - portfolio ✨🚀

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#8]
## 📌Note: we want to make all project's UI unique type so don't use bootstrap CSS if you want to use tailwind CSS therefore it's fine🤝👍
if you want to refer unique type UI then the below repository :
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/bc1d3e1a-f2e2-45f2-89ab-e596cd0596b7)

**Comment by TandinDev** [comment]
I can work on this. Can you please provide me more detail? I am fimilar with Tailwind, Material UI libraries.

**Comment by naijatechgirle** [comment]
Could you provide more details about this task? I'm keen to take it on.

**Comment by harshal255** [comment]
> Could you provide more details about this task? I'm keen to take it on.

in this task you have to create your responsive portfolio that contains your academic details , projects etc...

**Comment by Luwa-Tech** [comment]
hey @harshal255  can i work on this task?

**Comment by harshal255** [comment]
> hey @harshal255 can i work on this task?

Yeah sure

**Comment by Luwa-Tech** [comment]
Hi @harshal255 I see that you have closed this issue. can i still go ahead and create a PR.

**Comment by harshal255** [comment]
> Hi @harshal255 I see that you have closed this issue. can i still go ahead and create a PR.

ohh okay
