### ISSUE TITLE
Project doesn't opened on page 2 & page 3 

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#83]
These link work for page 1 only: 
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/43b6d752-fc98-407a-9b19-a52996591dd6)
![image](https://github.com/harshal255/Unique-Javascript/assets/93152436/e7529b96-95c9-4fcf-83b4-6e2acfba00e2)

**Comment by Diwanshumidha** [comment]
I can Work on this issue

**Comment by vr-varad21** [comment]
I would like to work on this project could  assign it to me?

**Comment by harshal255** [comment]
> I can Work on this issue

that issue is fixed
you can collaborate with another issue 👍👍

**Comment by Piyush07p** [comment]
can you assign this to me

**Comment by harshal255** [comment]
> can you assign this to me

No thanks that's functionality work good
