### ISSUE TITLE
Make a Search bar with good style to search project using topic name or project name 

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#89]
use es6+ filter method

**Comment by AryanBakliwal** [comment]
Hi @harshal255 I would like to work on this one; please assign me this

**Comment by harshal255** [comment]
> Hi @harshal255 I would like to work on this one; please assign me this

Okayy

**Comment by Piyush07p** [comment]
can you assign this to me

**Comment by AryanBakliwal** [comment]
Hi @harshal255, I've made a pr. Please review it and let me know if any change is required.

**Comment by harshal255** [comment]
> Hi @harshal255, I've made a pr. Please review it and let me know if any change is required.

Yes wait

**Comment by AryanBakliwal** [comment]
I've made a new pr with the latest commits.

#109

**Comment by harshal255** [comment]
> I've made a new pr with the latest commits.
> 
> #109

Okayy
