### ISSUE TITLE
Make two buttons for filter project & games

### ISSUE THREAD

**Issue by harshal255** [harshal255/Unique-Javascript#90]
project button -> display projects of all repository
games button -> display games of all repository
use es6+ features filter method

**Comment by sudhz** [comment]
Hi @harshal255, I am interested in working on this issue. Just to clarify, you want to implement two buttons called "PROJECTS" and "GAMES". When the PROJECTS button is clicked, only the projects are filtered and displayed on the screen out of all repositories, and when the GAMES button is clicked, only the games are filtered and displayed, right?

**Comment by harshal255** [comment]
Yeah you remember right


Harshal Kahar
On 21 Oct 2023, 10:59 AM +0530, Sudhanshu Makwana ***@***.***>, wrote:

Hi @harshal255<https://github.com/harshal255>, I am interested in working on this issue. Just to clarify, you want to implement two buttons called "PROJECTS" and "GAMES". When the PROJECTS button is clicked, only the projects are filtered and displayed on the screen out of all repositories, and when the GAMES button is clicked, only the games are filtered and displayed, right?

**Comment by SathvikKandadi** [comment]
Hey I am new to opensource and want to learn .Can you assign this issue to me?

**Comment by harshal255** [comment]
> Hey I am new to opensource and want to learn .Can you assign this issue to me?

Yeah sure

**Comment by Piyush07p** [comment]
can you assign it to me ,i will work for it

**Comment by sudhz** [comment]
Hi @harshal255, I have fixed this usse and made the pull request. Kindly close this issue and merge my PR.

**Comment by harshal255** [comment]
> Hi @harshal255, I have fixed this issue and made the pull request. Kindly close this issue and merge my PR.

Yeah wait
