### ISSUE TITLE
I have a good todo list app with good design, can you please add hacktoberfest to this issue assign it to me and then add accepted 

### ISSUE THREAD

**Issue by Blink29** [harshal255/Unique-Javascript#93]
<img width="821" alt="Screenshot 2023-10-21 at 1 51 40 PM" src="https://github.com/harshal255/Unique-Javascript/assets/115066832/4e785d8e-28bd-4af2-a38c-f220ac640c6d">
<img width="806" alt="Screenshot 2023-10-21 at 1 51 54 PM" src="https://github.com/harshal255/Unique-Javascript/assets/115066832/fccab063-cf6e-4905-96c5-1d8d3e5bed3c">

**Comment by harshal255** [comment]
> <img alt="Screenshot 2023-10-21 at 1 51 40 PM" width="821" src="https://user-images.githubusercontent.com/115066832/277096718-4e785d8e-28bd-4af2-a38c-f220ac640c6d.png"> <img alt="Screenshot 2023-10-21 at 1 51 54 PM" width="806" src="https://user-images.githubusercontent.com/115066832/277096729-fccab063-cf6e-4905-96c5-1d8d3e5bed3c.png">

Yeah sure
